# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  repositoryName: 'karpully'


stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
  # - job: Login
  #   displayName: Login
  #   dependsOn: Build
  #   pool:
  #     vmImage: ubuntu-latest
  #   steps:
  #     - task: Docker@2
  #       displayName: Login To Docker Hub Account
  #       inputs:
  #         command: login
  #         containerRegistry: |
  #           $(dockerHub)
  #         tags: $(tag)
  - job: Push
    displayName: Push
    dependsOn: Build
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: Docker@2
        displayName: Push The Image To Docker Hub
        inputs:
          command: push
          containerRegistry: |
            $(dockerHub)
          repository: $(repositoryName)
          tags: $(tag)
