# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  repositoryName: 'karpully/karpully-backend'


stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build The Image From Context
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: $(repositoryName)
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Push The Image To Docker Hub
      inputs:
          command: push
          containerRegistry: |
            $(dockerHub)
          repository: $(repositoryName)
          tags: $(tag)
